# Generated by Django 3.2.1 on 2021-05-05 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.IntegerField()),
                ('Sname', models.CharField(max_length=10)),
                ('Slocation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.IntegerField()),
                ('Cname', models.CharField(max_length=20)),
                ('Cfee', models.IntegerField()),
                ('Student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one_to_many_Relation.student')),
            ],
        ),
    ]
